// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CalculateDialog: typeof import('./components/Dialog/CalculateDialog.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HomeTitle: typeof import('./components/Home/HomeTitle.vue')['default']
    'ICarbon:dashboard': typeof import('~icons/carbon/dashboard')['default']
    'ICarbon:exit': typeof import('~icons/carbon/exit')['default']
    'ICarbon:home': typeof import('~icons/carbon/home')['default']
    'ICarbon:language': typeof import('~icons/carbon/language')['default']
    'ICarbon:login': typeof import('~icons/carbon/login')['default']
    'ICarbon:moon': typeof import('~icons/carbon/moon')['default']
    'ICarbon:rowDelete': typeof import('~icons/carbon/row-delete')['default']
    'ICarbon:sun': typeof import('~icons/carbon/sun')['default']
    ICarbonAdd: typeof import('~icons/carbon/add')['default']
    ICarbonTools: typeof import('~icons/carbon/tools')['default']
    ParticlesHome: typeof import('./components/Particles/ParticlesHome.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectForm: typeof import('./components/Form/SelectForm.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ToolItem: typeof import('./components/Tool/ToolItem.vue')['default']
  }
}
