// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CalculateDialog: typeof import('./components/Dialog/CalculateDialog.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    'ICarbon:rowDelete': typeof import('~icons/carbon/row-delete')['default']
    ICarbonAdd: typeof import('~icons/carbon/add')['default']
    ICarbonTools: typeof import('~icons/carbon/tools')['default']
    ILaLanguage: typeof import('~icons/la/language')['default']
    IMdiHomeSearchOutline: typeof import('~icons/mdi/home-search-outline')['default']
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectForm: typeof import('./components/Form/SelectForm.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ToolItem: typeof import('./components/Tool/ToolItem.vue')['default']
  }
}
